# Generated by Django 3.2.9 on 2021-11-27 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(default='Gaivota', max_length=20)),
                ('cidade', models.CharField(default='Itanhaém', max_length=20)),
                ('postal', models.PositiveBigIntegerField(default='11740-000')),
                ('senha', models.SlugField()),
                ('confirma_senha', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
