# Generated by Django 3.2.9 on 2021-11-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=11)),
                ('endereco', models.CharField(max_length=120)),
                ('numero', models.IntegerField(max_length=8)),
                ('complemento', models.IntegerField(max_length=10)),
                ('Bairro', models.CharField(max_length=20)),
                ('Cidade', models.CharField(max_length=20)),
                ('Cep', models.IntegerField(max_length=9)),
            ],
        ),
    ]
