# Generated by Django 3.2.9 on 2021-11-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='Cep',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='numero',
        ),
    ]
