# Generated by Django 3.2.9 on 2021-11-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211110_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='Postal',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='complemento',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='identidade',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='numero',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
