# Generated by Django 3.2.9 on 2021-11-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211110_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='Cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='Postal',
            new_name='postal',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='identidade',
        ),
    ]
