# Generated by Django 3.2.9 on 2021-11-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='Cad',
        ),
        migrations.RenameField(
            model_name='cad',
            old_name='CadastroCpf',
            new_name='CadCpf',
        ),
        migrations.RenameField(
            model_name='cad',
            old_name='CadastroId',
            new_name='CadId',
        ),
        migrations.RenameField(
            model_name='cad',
            old_name='CadastroNome',
            new_name='CadNome',
        ),
        migrations.RenameField(
            model_name='cad',
            old_name='CadastroNumber',
            new_name='CadNumber',
        ),
        migrations.RenameField(
            model_name='cad',
            old_name='CadastroRua',
            new_name='CadRua',
        ),
    ]
