# Generated by Django 3.2.9 on 2021-11-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('foto_produto', models.ImageField(upload_to='media/')),
                ('categoria_produto', models.CharField(choices=[('A', 'Básico'), ('B', 'Revestimento'), ('C', 'Louças'), ('D', 'Metais'), ('E', 'Hidráulica'), ('F', 'Elétrica'), ('G', 'Pintura'), ('H', 'Gesso'), ('I', 'Vidro'), ('J', 'Esquadrias'), ('K', 'Portas e janelas')], default='BASICO', max_length=2)),
                ('descricao_produto', models.CharField(max_length=500)),
            ],
        ),
    ]
